Repository sangam-weather/sangam-weather, pull requests merged in 2023-05, with the labels that each got.

#2 Chore: 프로젝트 셋업
  index.html
Labels: setting

#3 Feat: 날씨 API 불러오기
  app.js
  index.html
  server.js
Labels: feature

#4 Chore: 프로젝트 구조 변경
  .gitignore
  client/app.js
  client/index.html
  server/index.js
  server/package-lock.json
  server/package.json
Labels: setting

#5 Chore: 프로젝트 package 셋업, prettier 설정
  .eslintrc.js
  .prettierrc
  jsconfig.json
  package-lock.json
  package.json
  server/package-lock.json
  server/package.json
Labels: setting

#11 express구현,식당리스트API구현
  jsconfig.json
  package-lock.json
  package.json
  server/index.js
  server/restaurant.json
Labels: feature

#12 Chore:style 초기화
  client/app.js
  client/index.html
  client/src/style/reset.css
Labels: setting

#16 Style: 전체 레이아웃 스타일 구현
  client/app.js
  client/index.html
  client/src/img/logo.png
  client/src/style/common.css
Labels: style

#17 Fix: css 선택자 우선순위로 인해 파일 로드 순서 변경
  client/index.html
Labels: bug, style

#18 Feature/restaurant recommend
  client/src/recommend/index.html
  client/src/recommend/style.css
Labels: style

#21 Feat: 날씨 API 기능 구현
  client/app.js
  client/index.html
  client/src/img/02d.png
  client/src/img/weather/01d.png
  client/src/img/weather/01n.png
  client/src/img/weather/02d.png
  client/src/img/weather/02n.png
  client/src/img/weather/03d.png
  client/src/img/weather/03n.png
  client/src/img/weather/04d.png
  client/src/img/weather/04n.png
  client/src/img/weather/09d.png
  client/src/img/weather/09n.png
  client/src/img/weather/10d.png
  client/src/img/weather/10n.png
  client/src/img/weather/11d.png
  client/src/img/weather/11n.png
  client/src/img/weather/13d.png
  client/src/img/weather/13n.png
  client/src/img/weather/50d.png
  client/src/img/weather/50n.png
  client/src/wheather/index.html
  client/src/wheather/main.js
  client/src/wheather/style.css
  package-lock.json
  package.json
  server/index.js
  server/openWeather.js
Labels: feature

#25 Feat: 날씨 데이터에 따라 음식점 추천 기능 구현
  client/src/clothes/style.css
  client/src/recommend/index.html
  client/src/recommend/main.js
  client/src/wheather/main.js
  server/restaurant.json
Labels: feature

#30 Refactor: 코드 수정
  client/index.html
  client/src/wheather/main.js
Labels: reafactor

#31 Feat: favicon 추가
  client/favicon.ico
  client/index.html
Labels: UI

#35 Feat: 로딩 화면 구현
  client/index.html
  client/src/components/wheather/main.js
  client/src/public/style/common.css
Labels: feature
